### ISSUE TITLE
Hololens support on V1.2

### ISSUE THREAD

**Issue by yonghwan-shin** [pupil-labs/hmd-eyes#100]
Does new ver.1.2  hmd=eyes unity package supports hololens build?
On previous versions, there is a mark 'no hololnes support', but this one doesn't.

**Comment by pfaion** [comment]
Hi @yonghwan-shin,

with the release of the HoloLens 2 at the end of last year we have decided not to continue supporting the HoloLens with new releases. Version v1.1 was released shortly before this, so v1.2 is the first version reflecting this decision in the release notes (by not mentioning the HoloLens anymore).

That being said, the HoloLens 1 is supported until [HMD-Eyes v0.62](https://github.com/pupil-labs/hmd-eyes/releases/tag/v0.62) with Unity 2017.4LTS
The last release including a Hololens.unitypackage is [HMD-Eyes v0.5.1](https://github.com/pupil-labs/hmd-eyes/releases/tag/v0.5.1) and needs [Pupil Capture v1.7](https://github.com/pupil-labs/pupil/releases/tag/v1.7) to work. 

Please refer to the [legacy branch](https://github.com/pupil-labs/hmd-eyes/tree/legacy), checking the [readme](https://github.com/pupil-labs/hmd-eyes/blob/legacy/README.md) and [documentation](https://github.com/pupil-labs/hmd-eyes/blob/legacy/Developer.md).
