### ISSUE TITLE
VR add-on for Vive pro cannot be recognized after opening Pupil capture

### ISSUE THREAD

**Issue by ruw001** [pupil-labs/hmd-eyes#105]
if I connect the add-on to the computer and open Pupil Service, everything works perfectly. However, if I open Pupil Capture, the connection will be lost, and my PC warns me that the devices cannot be recognized by the computer, and it won't recover even if I open Pupil Service again. Same thing happened when I open the demo exe app. This is so weird, but it shouldn't be something wrong with the USB driver, right? Then what could be the cause?

**Comment by papr** [comment]
Hi, do I understand correctly that the first time you connect the add-on it works, then, without disconnecting it, changing the software causes it to stop working, and only disconnecting the hardware helps to restore it? Or does nothing help to restore it?

**Comment by ruw001** [comment]
Hi, sorry for the confusion. Yes, only plug out and re-plug in solved the problem. Sometimes even without opening Pupil Capture, the connection didn't seem to be very stable. It froze every several seconds especially if I was in motion. 

It turns out if I flip the USB-C connector on the add-on, the connection would be much stabler. But still, the camera is always 'disconnected' when I open Pupil Capture, though it won't influence Pupil Service anymore.

**Comment by papr** [comment]
Could you please share the `Home directory -> pupil_capture_settings -> capture.log` with us after attempting to get the cameras working in Pupil Capture?

**Comment by ruw001** [comment]
Sorry for this late update... The Pupil Capture works fine. I just forgot to select the eyes on the UI...
