### ISSUE TITLE
Accessing gaze data before calibration finishes

### ISSUE THREAD

**Issue by ruw001** [pupil-labs/hmd-eyes#107]
I noticed that I can access gaze data before calibration finishes, even though the data seems not very accurate. Is this because the calibration is updated dynamically along with data collection? I'm looking at [this code](https://github.com/pupil-labs/pupil/blob/e6a8856d19175c7c5ff553edc942b5cbfde3a0ef/pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_hmd.py) but I don't find anything that implies online model updating... Can someone please explain this to me? Thanks a lot!

**Comment by papr** [comment]
Hi, Capture restores the previous calibration from the session settings. Calibrations are only updated if you calibrate.
