### ISSUE TITLE
NullReferenceException Error with Connection?

### ISSUE THREAD

**Issue by CrazyDave4** [pupil-labs/hmd-eyes#108]
Each time I run the PupilDataDemo I get the following error:

```
NullReferenceException: Object reference not set to an instance of an object
PupilLabs.Helpers.DoubleFromDictionary (System.Collections.Generic.Dictionary`2[TKey,TValue] source, System.String key) (at Assets/plugin/Scripts/Helpers.cs:60)
PupilLabs.PupilData.ParseDictionary (System.Collections.Generic.Dictionary`2[TKey,TValue] dictionary) (at Assets/plugin/Scripts/PupilData.cs:130)
PupilLabs.PupilData..ctor (System.Collections.Generic.Dictionary`2[TKey,TValue] dictionary) (at Assets/plugin/Scripts/PupilData.cs:105)
PupilLabs.PupilListener.ReceivePupilData (System.String topic, System.Collections.Generic.Dictionary`2[TKey,TValue] dictionary, System.Byte[] thirdFrame) (at Assets/plugin/Scripts/PupilListener.cs:28)
PupilLabs.SubscriptionsController+Subscription.ParseData (System.Object s, NetMQ.NetMQSocketEventArgs eventArgs) (at Assets/plugin/Scripts/Subscription.cs:53)
NetMQ.NetMQSocket.InvokeEvents (System.Object sender, NetMQ.PollEvents events) (at <cd775f2ee43b4afd8cc83c9f5ddee1f4>:0)
NetMQ.NetMQSocket.Poll (System.TimeSpan timeout) (at <cd775f2ee43b4afd8cc83c9f5ddee1f4>:0)
NetMQ.NetMQSocket.Poll () (at <cd775f2ee43b4afd8cc83c9f5ddee1f4>:0)
PupilLabs.SubscriptionsController+Subscription.UpdateSocket () (at Assets/plugin/Scripts/Subscription.cs:62)
PupilLabs.SubscriptionsController.UpdateSubscriptionSockets () (at Assets/plugin/Scripts/SubscriptionsController.cs:118)
PupilLabs.SubscriptionsController.Update () (at Assets/plugin/Scripts/SubscriptionsController.cs:47)
```

It takes to the "Helpers.cs" file. I'm using Pupil Capture v3.5.1. Any ideas would be appreciated.

**Comment by papr** [comment]
Hi @CrazyDave4 

> PupilLabs.PupilData.ParseDictionary (System.Collections.Generic.Dictionary`2[TKey,TValue] dictionary) (at [Assets/plugin/Scripts/PupilData.cs:130](https://github.com/pupil-labs/hmd-eyes/blob/master/plugin/Scripts/PupilData.cs#L130))

This line points to a comment in the current implementation. This leads me to think that you might be using an incompatible version of hmd eyes. Pupil Capture v3.0 and newer require hmd-eyes v1.4 or newer.

**Comment by CrazyDave4** [comment]
> Hi @CrazyDave4
> 
> > PupilLabs.PupilData.ParseDictionary (System.Collections.Generic.Dictionary`2[TKey,TValue] dictionary) (at [Assets/plugin/Scripts/PupilData.cs:130](https://github.com/pupil-labs/hmd-eyes/blob/master/plugin/Scripts/PupilData.cs#L130))
> 
> This line points to a comment in the current implementation. This leads me to think that you might be using an incompatible version of hmd eyes. Pupil Capture v3.0 and newer require hmd-eyes v1.4 or newer.

Thank you @papr ! Yes it stopped working right after I updated the software to v3.5. Just switched back to an older version (v1.23) and the problem was gone. Thanks for your reply. Happy new year )
