### ISSUE TITLE
What is the best calibration practice?

### ISSUE THREAD

**Issue by ruw001** [pupil-labs/hmd-eyes#110]
I found the calibration accuracy with the original calibration interface is not very high, so I'm wondering if that's the best result I can get. I then tried generating a 9x9 target grid with 10 degree spacing, but the accuracy is still not high enough for applications. I tested the system on a friend and the mean error is 6.95 degree (SD=11.25) across the visual field they can see. For ±20 degree in central area, the mean error is 5.25 degree (SD=3.64). Does this align with your evaluation? if not, how can I improve it?

Another question, if the user is near sighted, will their glasses affect the calibration?

**Comment by papr** [comment]
Hi @ruw001 

Apologies for the delayed response. Could you share an example Pupil Capture recording of the calibration and validation with data@pupil-labs.com? We will be able to give specific feedback upon the review of the recording.

**Comment by ruw001** [comment]
Sure. I'll attach more information in the email
