### ISSUE TITLE
Eye Calibration Faild in Unity 2021.3.16f1 using Quest Pro Headset

### ISSUE THREAD

**Issue by AyaAbdulnasser** [pupil-labs/hmd-eyes#115]
Hello,
I am trying to use hmd_eyes to access the eye features using Quest Pro (Unity 2021.3.16f1 ver.

However, I am using GazeDemoScene for eye calibration it shows a connected message, and I press the C key, and then the calibration starts, but the calibration always fails. I also switched API to **.NET Framework** and tried many things but still the same.
I have attached some pictures of that problem. Could you please guide me on that?

![E2](https://user-images.githubusercontent.com/121787161/212585706-499904e1-da4d-4eb9-bafc-a7f175c253ff.PNG)
![E3](https://user-images.githubusercontent.com/121787161/212585711-6186f042-14e7-4a32-9bb0-a096787e385d.PNG)
![E4](https://user-images.githubusercontent.com/121787161/212585712-20ba5a4f-d53f-488e-a64a-c12ec483d288.PNG)
![E5](https://user-images.githubusercontent.com/121787161/212586202-605162f6-b65a-4990-9ac8-2bcde157968d.PNG)

**Comment by papr** [comment]
Hi! @AyaAbdulnasser 
It looks like you are starting the calibration from within Pupil Capture. While this is the right approach when you are using the Pupil Core headset, the hmd calibration should be started through the gaze hmd eyes demo. You should see the instructions being displayed in the unity view.

**Comment by AyaAbdulnasser** [comment]
Thank you for your reply, I appreciate that. Could you please share the link for the instructions in the unity view that you mean?

**Comment by papr** [comment]
![Capture](https://user-images.githubusercontent.com/168390/213189663-757d88be-12be-46ce-8116-e6dc028f7c34.PNG)

@AyaAbdulnasser 
0. open your Unity project and add the plugin based on the [instructions](https://github.com/pupil-labs/hmd-eyes/blob/master/docs/Developer.md#adding-hmd-eyes-to-existing-projects)
1. Select the corresponding demo folder from the asset list
2. Open the demo file
3. Hit Play
4. Wait for Unity to connect to Capture. Then follow the instructions on the Unity main view (e.g. press C in Unity to start calibrating)

**Comment by AyaAbdulnasser** [comment]
Thank you so much for the clarification, you are really helpful. 
I have done the steps you mentioned and when I press the C key the calibration starts, and when the calibration finishes it gives me a message that the **calibration is Failed**, like what shows in the attached picture.

![P1](https://user-images.githubusercontent.com/121787161/213365307-a425bad2-43e6-4882-bb41-dcbe671c81ef.PNG)

**Comment by papr** [comment]
That can have multiple reasons. Please check the Pupil Capture log. Most likely, the issue will be bad pupil detection. Please read more about it [here](https://docs.pupil-labs.com/core/#_3-check-pupil-detection).

Feel free to share a [raw Capture recording](https://docs.pupil-labs.com/core/software/pupil-capture/#recording) with us that demonstrates the calibration. For that, simply hit the `R` button in Pupil Capture before pressing the `C` button in Unity. After the calibration has failed, hit `R` in Capture again to stop the recording. Finally, upload the recording folder and share a link with data@pupil-labs.com We will review the recording and come back to you with concrete feedback.

I will close this issue as this is not a technical issue with hmd-eyes.
