### ISSUE TITLE
Position of Calibration marker out of sight

### ISSUE THREAD

**Issue by MaxudSc** [pupil-labs/hmd-eyes#15]
Hello,
I have the issure that the markers cant be seen through my pupil labs VR Vive headset. The objects are out of range.
Is there a quick way to fix that?

**Comment by mkassner** [comment]
Yes. You can adjust the sites in the unity source: 
https://github.com/pupil-labs/hmd-eyes/blob/master/unity_integration_calibration/Assets/Scripts/PupilGazeTracker.cs#L388-L392

**Comment by willpatera** [comment]
Closing. Will be fixed in updated plugin.
