### ISSUE TITLE
3D calibration without z component?

### ISSUE THREAD

**Issue by PolynomialDivision** [pupil-labs/hmd-eyes#24]
Hi,
I think the calibration is only sending 2D data and no depth (z component)?

**Comment by kornellvarga** [comment]
Hi,
There are two calibration methods in my fork.
The 2D calibration method sends a float array with two elements.
The 3D one sends a float array with 3 elements.
Before completing the merge you can check the 3D calibration on my fork.

**Comment by PolynomialDivision** [comment]
Thanks I wil try tomorrow :D
