### ISSUE TITLE
NetMQ problem when calibration starts

### ISSUE THREAD

**Issue by joobei** [pupil-labs/hmd-eyes#29]
When I press 'c' to begin calibration there is an exception error. 

TerminatingException: CheckContextTerminated - yes, is terminated.
NetMQ.Core.SocketBase.CheckContextTerminated ()
NetMQ.Core.SocketBase.TrySend (NetMQ.Msg& msg, TimeSpan timeout, Boolean more)
NetMQ.NetMQSocket.TrySend (NetMQ.Msg& msg, TimeSpan timeout, Boolean more)
NetMQ.OutgoingSocketExtensions.Send (IOutgoingSocket socket, NetMQ.Msg& msg, Boolean more)
NetMQ.OutgoingSocketExtensions.SendFrame (IOutgoingSocket socket, System.Byte[] data, Int32 length, Boolean more)
NetMQ.OutgoingSocketExtensions.SendMoreFrame (IOutgoingSocket socket, System.Byte[] data, Int32 length)
NetMQ.OutgoingSocketExtensions.SendMultipartMessage (IOutgoingSocket socket, NetMQ.NetMQMessage message)
PupilGazeTracker._sendRequestMessage (System.Collections.Generic.Dictionary`2 data) (at Assets/Scripts/PupilGazeTracker.cs:1788)
PupilGazeTracker.StartCalibration () (at Assets/Scripts/PupilGazeTracker.cs:2096)
PupilGazeTracker.Update () (at Assets/Scripts/PupilGazeTracker.cs:880)

This is the offending line:

https://github.com/pupil-labs/hmd-eyes/blob/65903284a455de75e32594b53631aff1b60ba742/unity_pupil_plugin/Assets/Scripts/PupilGazeTracker.cs#L2096

--System--
Unity 5.6.2f1
Windows 10 x64
pupil_v0912_windows_x64
Latest Drivers

**Comment by mkassner** [comment]
I believe this code is long replaced.
