### ISSUE TITLE
PupilTools delegate typos

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/hmd-eyes#36]
I'm just learning the delegate system in Unity, but I think there might be a typo in the following code [found here](https://github.com/pupil-labs/hmd-eyes/blob/master/unity_pupil_plugin/Assets/pupil_plugin/Scripts/Networking/PupilTools.cs#L25-L28):

```C#
	public static event OnCalibrationEndDeleg OnCalibrationEnded;
	public static event OnCalibrationEndDeleg OnCalibrationFailed;
	public static event OnConnectedDelegate OnConnected;
	public static event OnConnectedDelegate OnDisconnected;
```

Again, I'm a novice here, so there's a chance that there's a good reason for this, but my intuition is that OnCalibrationFailed should be an event of OnCalibrationFailedDeleg, not OnCalibrationEndDeleg. Same thing with OnDisconnected and OnDisconnectedDelegate.

**Comment by AndreNicolai** [comment]
Thanks for the catch, @cboulay !

I had seen the misnomer for the delegates concerning disconnect (when I changed it from OnDisconnected to OnDisconnecting), but missed the one for OnCalibrationFailed.

Just committed the fix.
