### ISSUE TITLE
update python example to python3

### ISSUE THREAD

**Issue by mkassner** [pupil-labs/hmd-eyes#38]
The example is for reference only but having in in python3 is still required to make it work.

**Comment by papr** [comment]
Should also be updated to be compatible with https://github.com/pupil-labs/pupil/pull/1867

@romanroibu Please use the Service integration notebook as a reference to fix this issue.

**Comment by pfaion** [comment]
@papr I think the code is python3 compatible (although classes still inherit from `object`).
I developed and tested #97 on python3.

-- closed by #97
