### ISSUE TITLE
EyeData.get_Raw3D () returns null after 3D Calibration

### ISSUE THREAD

**Issue by xstreck1** [pupil-labs/hmd-eyes#39]
On an HTC Vive, in the unity_pupil_plugin_vr, in the "3D Calibration Demo" scene, after a successful calibration the MarketWith3DCalibration.cs starts throwing NullPtrException on EyeData.get_Raw3D ().

Does not affect the 2D Calibration.

Tested with
- Unity 2017.3.0 and 2017.2.1
- the 1866fae commit and the v0.3.0.1 release commit
- the 1.1.2 and 1.2.7 Pupil Service (the 1.2.7 does not actually finish the calibration at all so that's not affected).

Editor log attached: 
[Editor.log](https://github.com/pupil-labs/hmd-eyes/files/1652690/Editor.log)
 .

**Comment by AndreNicolai** [comment]
Thanks for reporting the issue.
I was able to reproduce the bug with the v0.3.0.1 release, but the specified commit was the one that should have prevented the "throw" by adding a check for "null".
