### ISSUE TITLE
Can you tell the size of the pupil and the angle of the eye position?

### ISSUE THREAD

**Issue by loolsasy** [pupil-labs/hmd-eyes#41]
Thank you for your last help.
Thanks to that, I am now getting the Gaze value without any problems.
There are three kinds of help I need right now.
 
1. Is there a way to measure pupil size?
I want to find the pupil size as well as the eye position.

2. I am getting the value of Gaze. How much of this value is actually moving and can I get the angle moving?

3. https://www.youtube.com/watch?v=2cTJ1IWmOGY
I want to get the image of Pupil Service from Unity like the video of this link.
It can be received in real time, but it is okay to have only one image of both eyes when you want.
Unity_pupil_plugin_vr / Assets / pupil_plugin / Scripts / Pupil / FramePublishing.cs It seems that you are trying to get an image from this class, but it does not seem to have been developed yet.
Can you tell when it will be developed?

I would like you to let me know if you can easily read the document.

My environment is using win10, unity, pupil version 1.3.9.

**Comment by AndreNicolai** [comment]
Have a look at [Pupil - Data Format](https://docs.pupil-labs.com/#looking-at-the-data) for other information you can get from Pupil (e.g. pupil size). Let me highlight, though, that the "diameter" unit for 2D calibration is pixels, while "diameter_3d" will give you the values in mm.

As for getting the eye camera images:
You were popinting to the correct FramePublishing class, but with today's commit to the master branch, we implemented a quick-to-read example on how to access the image streams. Please download the newest version and have a look at FramePublishing.unity respectively FramePublishingDemoManager.cs

Hope this help!

**Comment by loolsasy** [comment]
I'm still grateful for your help.
The image succeeded in obtaining the desired texture in FramePublishing.unity.
However, there is no way to determine the pupil size.
I checked the value of Diameter () or _3D.Circle.Radius () in PupilData.cs, ​​but it only returns 0. I tried CalibrationMode in 3D, but the result seems to be the same.
PupilCapture It looks like the size of the pupil and the size of the iris are found on the screen. I would like to use it in the Unity Plugin.
I need your help. :-)

**Comment by AndreNicolai** [comment]
The PupilData methods you mentioned are left-overs from the past (which should maybe be removed). PupilData currently only exemplifies how to handle gaze information. If you want to get information such as 'diameter', you have to subscribe to "pupil.". The dictionary you receive will include values for 'diameter' and you can access it by e.g. adapting the following method from PupilTools:
	public static float ConfidenceForDictionary(Dictionary<string,object> dictionary)
	{
		object conf0;
		dictionary.TryGetValue ("confidence", out conf0);
		return (float)(double)conf0;
	} 
Just replace "confidence" with "diameter"

**Comment by loolsasy** [comment]
I wrote the following code in PupilTools.cs,
`public static float DiameterForDictionary(Dictionary<string, object> dictionary)
{
          object conf0;
          dictionary.TryGetValue("diameter", out conf0);
          return (float)(double)conf0;
}
public static float Diameter(int eyeID)
     {
          if (eyeID == PupilData.rightEyeID && pupil0Dictionary != null)
               return DiameterForDictionary(pupil0Dictionary);
          else if (eyeID == PupilData.leftEyeID && pupil1Dictionary != null)
               return DiameterForDictionary(pupil1Dictionary);
          else
               return 0;
     }
`
The desired result could be obtained.
It appears that only the result measured at the time of calibration appears.
But what I really want is to find the size of the pupil that changes in real time.

For example, if the background changes from black to white, the size of the pupil will decrease.
I want to measure changes in pupil size in real time.

And, if possible, I wonder if the size of the pupil can be measured by dividing it into a horizontal value and a vertical

**Comment by AndreNicolai** [comment]
We actually have no implementation in the Unity plugin to record value changes. So this would be something you have to implement on your own. But the code you posted is a good start.
What you can also get from the dictionary is a timestamp, which might be helpful for this, as well.

As for the question about values for horizontal and vertical extend:
It would have been too complicated to post a solution, here, so I just commit an additional Unity scene and script for subscribing to "pupil.". [Have a look at it:](https://github.com/pupil-labs/hmd-eyes/blob/master/unity_pupil_plugin_vr/Assets/pupil_plugin/Scripts/PupilDemo.cs)
The dictionaries you receive also contain an object named "ellipse" that offers the information you need. The axes define the length of the major and minor axis of that ellipse (with "diameter" representing the major axis value). As the axes do not correspond to horizontal and vertical extend, you will also need to use "angle", which indicates how much the ellipse is turned away from the horizontal axis. ( [This visualization might help](https://docs.opencv.org/3.0-beta/modules/imgproc/doc/drawing_functions.html#ellipse) )

Hope this helps!

**Comment by AndreNicolai** [comment]
@loolsasy I have not heard back from you in a while. Did my last comment and the new Unity scene help you with your endeavor?

Can we close this issue?

**Comment by loolsasy** [comment]
Oh, I'm sorry for the delay.
I was delayed to apply the new plug-in.
Thanks to your help, I was able to implement the functionality I wanted.
You can close this post.
