### ISSUE TITLE
Material Path

### ISSUE THREAD

**Issue by Spyrko** [pupil-labs/hmd-eyes#42]
In the file "unity_pupil_plugin_hololens/Assets/pupil_plugin/Scripts/Pupil/PupilMarker.cs" you have the line:

`material = new Material (Resources.Load<Material> ("Materials/MarkerMaterial"));`

But there is no such file. If you adjust the path to just "MarkerMaterial" everything works fine.
Maybe you should fix this.

**Comment by AndreNicolai** [comment]
Thanks for pointing this out!
I am working on a new release version, which will have this corrected.
