### ISSUE TITLE
PupilTools FloatFromDictionary does not use key parameter

### ISSUE THREAD

**Issue by mikkeyboi** [pupil-labs/hmd-eyes#45]
See [here](https://github.com/pupil-labs/hmd-eyes/blob/master/unity_pupil_plugin_vr/Assets/pupil_plugin/Scripts/Networking/PupilTools.cs#L229-L234)

```C#
	public static float FloatFromDictionary(Dictionary<string,object> source, string key)
	{
		object value_o;
		source.TryGetValue ("confidence", out value_o);
		return (float)(double)value_o;
	}
```

It's almost certainly true that `"confidence"` needs to be replaced by `key`. I'm surprised this hasn't come up before because it seems to affect timestamps in recordings [here](https://github.com/pupil-labs/hmd-eyes/blob/d35e7ed3c3bab9e3e9d31e36e610dff3097fe446/unity_pupil_plugin_vr/Assets/pupil_plugin/Scripts/Networking/PupilTools.cs#L108).

**Comment by cboulay** [comment]
Sorry, it was me but I accidentally posted this under my colleague's account.

**Comment by mkassner** [comment]
@cboulay Thank you for the input!  Would you mind making a PR and we will merge it!
