### ISSUE TITLE
Make confidence threshold user-configurable

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/hmd-eyes#46]
Our game/experiment generates an error when the subject looks away from the fixation point and it would be great if that didn't happen during blinks or momentary tracking glitches. It seems the easiest way to do this would be to throw away data that didn't pass a confidence threshold.

In fact this is already done [here](https://github.com/pupil-labs/hmd-eyes/blob/ff1fa3442168efd64d164ac3d6c8168077cb12e9/unity_pupil_plugin_vr/Assets/pupil_plugin/Scripts/Networking/Connection.cs#L176-L177) (I think) but it is hard-coded to 0.6. Please make this user-configurable.

**Comment by mkassner** [comment]
@cboulay  same as the other issue, it you make this PR I d love to merge it!

**Comment by cboulay** [comment]
I guess we sneaked this in with #52 . It's now a public member variable in Networking/Connection.cs and can be modified in PupilSettings.
