### ISSUE TITLE
Blink data

### ISSUE THREAD

**Issue by YuanjieWu** [pupil-labs/hmd-eyes#53]
I'm trying to get blink data through blink demo, but there is no logout message(blink detected, etc..) in the unity console. How can I get blink data? I can get the gaze data after calibration.

**Comment by mkassner** [comment]
Hi, we have recently identfied the bug and will push a fix with the next version of Pupil Capture. This should happen within the next 10 days.

**Comment by fx-lange** [comment]
Hi @YuanjieWu, although this issue is quite old I'm happy to inform you that it is fixed :) Just tested the blink demo with Pupil Capture 10.1 and hmd-eyes v0.61.

**Comment by patryk191129** [comment]
I've already tested it with the latest version and still can not detect blinking
