### ISSUE TITLE
Getting values in base_data from PupilTools.gazeDictionary

### ISSUE THREAD

**Issue by joeinmbb** [pupil-labs/hmd-eyes#56]
I'm trying to get 'diameter' value in 'base_data' from 'PupilTools.gazeDictionary' after 2D calibration process.
But it seems that 'base_data' can't be cast in spite of using function BaseData() or DictionaryFromDictionary() in PupilTools.
How can I get values in base_data from PupilTools.gazeDictionary?

--Environment--
OS: Windows 10 x64
Unity: 2017.3.1
Pupil Capture: v1.8-26

**Comment by fx-lange** [comment]
For future reference, in hmd-eyes v1.0+ you can use `PupilListener` + `PupilData` to access Pupil data like diameter.
