### ISSUE TITLE
Calibration always fails in .NET 4.x API compatibility level; Missing MessagePack types under .NET 2.0

### ISSUE THREAD

**Issue by Loonachip** [pupil-labs/hmd-eyes#61]
Hello

I have a minimal Unity  project with imported only SteamVR plugin and hmd-eyes plugin. 
If there is chosen API compatibility level '.NET Standard 2.0', there appears massive wave of missing types in MessagePack (those from .Net 4). 
Once I switch into .NET 4.x, all errors dissappears, but then every calibration is being failed with result shown in picture below
![apibug](https://user-images.githubusercontent.com/18331253/53109083-77735a80-3538-11e9-89a4-b045919b5c2c.png)

Problem with failing was existing there for some time using .NET 4, but MessagePack missing types has appeared when Steam released update of SteamVR app.

Unity v. 2018.3.5f1
SteamVR unity plugin v. 2.2.0
hmd-eyes plugin v. latest
pupil service v. 1.10-20-g6936560
OpenVR v. 1.0.3

**Comment by fx-lange** [comment]
hi @Loonachip,

I can reproduce your issue regarding the API compatibility level '.Net Standart 2.0' - for now we still recommend Unity 2017.4 running .NET 3.5. Could you please give this a try - at least for testing. We are currently working on an plugin overhaul, with support for 2018.3.

**Comment by Loonachip** [comment]
It's workink properly on 2017.4.21, great thanks for response :)
I'm looking forward to have support for newest version, so good luck!

**Comment by fx-lange** [comment]
Hi @Loonachip, we launched an alpha release today, supporting Unity 2018.3 running .NET 4.x. Feel free to give it a try.
