### ISSUE TITLE
ArgumentOutOfRangeException -> AsyncIO outdated

### ISSUE THREAD

**Issue by cynicer** [pupil-labs/hmd-eyes#63]
For a project I used your code and deployed the Unity project to my Android device. After receiving data for up to 2 minutes flawlessly, it just stops without printing any information or raising any exception. The SubscriberSocket in the connection just doesn't have new data to deliver.

However, in very rare cases I managed to get an exception:
`03-01 10:40:00.086 13450 13594 E Unity   : ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
03-01 10:40:00.086 13450 13594 E Unity   : Parameter name: millisecondsTimeout
03-01 10:40:00.086 13450 13594 E Unity   :   at System.Threading.WaitHandle.WaitOne (System.Int32 millisecondsTimeout, System.Boolean exitContext) [0x00013] in <d7ac571ca2d04b2f981d0d886fa067cf>:0
03-01 10:40:00.086 13450 13594 E Unity   :   at System.Threading.WaitHandle.WaitOne (System.Int32 millisecondsTimeout) [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0
03-01 10:40:00.086 13450 13594 E Unity   :   at System.Collections.Concurrent.BlockingCollection1[T].TryTake (T& item, System.Int32 timeout) [0x00087] in <20599ba1ee5a49a39b6681a06025b37e>:0
03-01 10:40:00.086 13450 13594 E Unity   :   at AsyncIO.DotNet.CompletionPort.GetMultipleQueuedCompletionStatus (System.Int32 timeout, AsyncIO.CompletionStatus[] completionStatuses, System.Int32& removed) [0x0002d] in <20599ba1ee5a49a39b6681a06025b37e>:0
03-01 10:40:00.086 13450 13594 E Unity   :   at NetMQ.Core.Utils.Proactor.Loop () [0x00014] in <3f7bfb8e0fb64c5398262c3b6b8f6c44>:0
03-01 10:40:00.086 13450 13594 E Unity   :   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <d7ac571ca2d04b2f981d0d886fa067cf>:0
03-01 10:40:00.086 13450 13594 E Unity   :   at System.`

It seems like your AsyncIO DLL is rather outdated. For me the 0.1.69 .NET 4.0 version from (https://www.nuget.org/packages/AsyncIO/) works fine. Maybe someone bothers to update the dependency.

Regards,
Marcel

**Comment by fx-lange** [comment]
Thanks @cynicer for the detailed report and suggestion. We updated our dependencies and will ship it with the next release.

**Comment by fx-lange** [comment]
Solved in current master (hmd-eyes v1.0).
