### ISSUE TITLE
alpha - No connection if only 1 eye window is open in pupil service.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/hmd-eyes#67]
The solution would be to check to make sure both eye windows are open in service and, if not, issue the appropriate error message.

**Comment by fx-lange** [comment]
Hi @performlabrit, I can't reproduce your issue. When I run hmd-eyes alpha and pupil service with 0 or 1 eyes the connection still works.

**Comment by performlabrit** [comment]
Yes, apologies for not removing this because I too an unable to reproduce.
I'm not sure what was causing the original issue, but this ticket can be
closed.

----------------------

Gabriel J. Diaz, Ph.D.
Assistant Professor
Rochester Institute of Technology
Chester F. Carlson Center for Imaging Science

*Founder of PerForM Labs*
*Click for demos.* <https://www.cis.rit.edu/performlab/>

Office 2108, Building #76
Rochester, NY 14623
Office: (585) 475-6215
gabriel.diaz@rit.edu
