### ISSUE TITLE
Alpha:  FormatterNotRegisteredException 

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/hmd-eyes#70]
In the Gaze Demo, I do get the "connected" message, but the eye images are not visible, and when I try and calibrate, I get the following message:

FormatterNotRegisteredException: System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] is not registered in this resolver. resolver:StandardResolver
MessagePack.FormatterResolverExtensions.GetFormatterWithVerify[T] (MessagePack.IFormatterResolver resolver) (at Assets/Plugins/Pupil/3rd-party/MessagePack/IFormatterResolver.cs:35)
MessagePack.MessagePackSerializer.Serialize[T] (T obj, MessagePack.IFormatterResolver resolver) (at Assets/Plugins/Pupil/3rd-party/MessagePack/MessagePackSerializer.cs:64)
MessagePack.MessagePackSerializer.Serialize[T] (T obj) (at Assets/Plugins/Pupil/3rd-party/MessagePack/MessagePackSerializer.cs:55)
PupilLabs.RequestController+Request.SendRequestMessage (System.Collections.Generic.Dictionary`2[TKey,TValue] data) (at Assets/Plugins/Pupil/Scripts/Request.cs:76)
PupilLabs.RequestController.StopPlugin (System.String name) (at Assets/Plugins/Pupil/Scripts/RequestController.cs:118)
PupilLabs.FrameListener.Disable () (at Assets/Plugins/Pupil/Scripts/FrameListener.cs:53)
PupilLabs.RequestController.Disconnect () (at Assets/Plugins/Pupil/Scripts/RequestController.cs:90)
PupilLabs.RequestController.OnDisable () (at Assets/Plugins/Pupil/Scripts/RequestController.cs:45)

**Comment by performlabrit** [comment]
The next day... unable to replicate!

**Comment by fx-lange** [comment]
Hi @performlabrit, just for reference. This error might have been caused by your scripting runtime settings. As mentioned in the release notes:

`Due to an issue with MessagePack, the default project setting for ProjectSettings/Player/Configuration/API Compatibility Level is currently not supported and needs to be set to .NET 4.x.`
