### ISSUE TITLE
"Diameter" Values

### ISSUE THREAD

**Issue by ChisChris** [pupil-labs/hmd-eyes#74]
Hello,
I opened the PupilDataDemo scene in Unity and I tried to display the "diameter" values. What I get is a float between around 20 and 140. 
While it is written that the pupil is operating in mm.
Is it a matter of measurement unit or the values do not represent the actual pupil diameter?

In the pupil_capture application, I see the correct values (from around 0 to 8mm).
Thank you!

**Comment by papr** [comment]
Hi @ChisChris 
These are probably 2d diameter values whose unit is pixels. My guess is that the `PupilDataDemo scene` displays value from the `diameter` pupil field instead of the `diameter_3d` pupil field. Unfortunately, I do not know the code base well enough to point you to the exact location.

**Comment by ChisChris** [comment]
Thanks for the help @papr! I will look it up a bit more and let you know in case I find anything.

**Comment by fx-lange** [comment]
For future reference, `PupilData` offers Diameter (image pixel) and Diameter3d (in mm).
