### ISSUE TITLE
Alpha/Beta:  In gazeVisualizer.cs, updating marker position to hit.point is a misleading representation of gaze accuracy.

### ISSUE THREAD

**Issue by performlabrit** [pupil-labs/hmd-eyes#81]
Your methods for gaze visualization are biasing estimates of gaze accuracy in your favor.

And, here's a brief explanation...

Collisions are detected by casting a sphere of a fixed size in the direction of the gaze ray.

The gaze blob is then set to the position of hit.point (the collision location).
...which is offset from the gaze ray!

![Drawing](https://user-images.githubusercontent.com/8962011/62483691-4e612200-b786-11e9-9cb6-943a7efa8485.jpeg)

The more honest way to do this would be to place the gaze blob at the distance of the hit.point, but keep it centered on the gaze ray.

[The code I'm referencing is here:](https://github.com/pupil-labs/hmd-eyes/blob/b5273dedf9f1662ef0f2eccdd6b511f57ce1dc5d/plugin/Scripts/GazeVisualizer.cs#L129)

```
if (Physics.SphereCast(origin, sphereCastRadius, direction, out RaycastHit hit, Mathf.Infinity))
            {
                Debug.DrawRay(origin, direction * hit.distance, Color.yellow);

                projectionMarker.position = hit.point;
}
```

**Comment by fx-lange** [comment]
hi @performlabrit - thanks for your report. 

the current visualization is a mix of showing the gaze direction and highlighting the object being hit by the gaze "ray". you are right that the current simplification can be misleading and we will look into it for the next release. thanks for pointing it out.

**Comment by performlabrit** [comment]
Here is some representative code.
GazeDirectionCombined is the normalized gaze direction within the world frame.


`if (Physics.SphereCast(Camera.main.transform.position, sphereCastRadius, GazeDirectionCombined, out RaycastHit hit, Mathf.Infinity))
                    {

                        transform.position = Camera.main.transform.position + GazeDirectionCombined * hit.distance;

                        float diameterM = Mathf.Tan(Mathf.Deg2Rad * (objSizeDegs/2.0f)) * hit.distance * 2.0f;
                        transform.localScale = new Vector3(diameterM, diameterM, diameterM);
                    }
                    else
                    {
                        transform.position = Camera.main.transform.position + GazeDirectionCombined * objDefaultDist;
                        float diameterM = Mathf.Tan(Mathf.Deg2Rad * (objSizeDegs/2.0f)) * objDefaultDist * 2.0f;
                        transform.localScale = new Vector3(diameterM, diameterM, diameterM);
                    }`

**Comment by fx-lange** [comment]
thanks again @performlabrit. 

updated + more detailed documentation in latest develop branch
