### ISSUE TITLE
Start File Sources in Capture via notification

### ISSUE THREAD

**Issue by dalind** [pupil-labs/hmd-eyes#88]
Hi,

I was wondering if it possible to subscribe to previously recorded data. I want to record multiple sessions, and then get Player or Capture (or Service) to replay this data. The playback should be triggered from Unity.

Player can display the recorded data, but not send it to Unity.  
I can point the sources in Capture to the recordings, but that process does not scale and cannot be triggered from Unity.

Essentially, I would like to achieve a workflow where I e.g., load data into capture and then send a 'start playback' command, and get this data streamed into Unity.\

//Note that this is not specific to HMD Eyes, but I use it in that context. I can also close this issue and open one in the general pupil repo.

Thanks for your help!

Best,
David

**Comment by papr** [comment]
Hi @dalind 
> I can point the sources in Capture to the recordings, but that process does not scale and cannot be triggered from Unity.

Could you elaborate on that point? What do you mean by "point the sources" and why does it not scale?

What is the purpose of this playback? Do you want to use it for debugging purposes?

**Comment by dalind** [comment]
_Point to sources:_
In the backend manager, I can point the Manager to 'Video File Source', and then on 'Activate Source', I can select the individual files (world video, eye0, eye1) from a previous recording.

Goal:
I want to record data in VR for multiple users and store all interactions, incl. gaze. After the experiment, I would like to replay what users did, and where they looked at. This will allow me to extract gaze data from multiple angles, and possibly for multiple cameras. In our context, we want to use it to test a ML model, and extract a data set.

**Comment by papr** [comment]
@dalind Did you know that you can start the Video File Sources with notifications instead of manually selecting the videos?

The notification structure would look like this for the world video:
```py
{
"subject": "start_plugin",
"name": "File_Source",
"args": {"source_path": VIDEO_PATH}
}
```
and like this for each eye video:
```py
{
"subject": "start_eye_plugin",
"target": "eye0",  # or eye1
"name": "File_Source",
"args": {"source_path": VIDEO_PATH}
}
```

**Comment by dalind** [comment]
@papr :
I did not know this, looks like exactly what I need. I have been trying since you wrote, but it seems like Capture does not take my command. Console outputs "world - [INFO] video_capture.file_backend: Video has ended." immediately after I load the video.

Below is my C# code. Note that when I paste the path into Capture (Manager, Video File Source), the recording is recognized. Is there a reference / documentation for the notifications I can check out? 


```
RequestController.Send(new Dictionary<string, object>
{ 
    { "subject","start_plugin" },
    { "name", "File_Source" },
    { "args", new Dictionary<string, object>
        {
            {"source_path:", @"D:\Work\my-double-checked-correct-path\log\log_20200212-1612\gaze\000\world.mp4"}
        }
    }
});
```

**Comment by papr** [comment]
@pfaion Could you please check this out tomorrow?

**Comment by pfaion** [comment]
I have been able to successfully start the File_Source with a video file from the following Python script:

```python
from time import sleep, time
import msgpack as serializer
import zmq

# Setup zmq context and remote helper
ctx = zmq.Context()
socket = zmq.Socket(ctx, zmq.REQ)
socket.connect("tcp://127.0.0.1:50020")

def notify(subject, **data):
    topic = f"notify.{subject}"
    notification = dict(subject=subject, **data)
    payload = serializer.dumps(notification, use_bin_type=True)
    socket.send_string(topic, flags=zmq.SNDMORE)
    socket.send(payload)
    result = socket.recv_string()

notify(
    subject="start_plugin",
    name="File_Source",
    args={"source_path": r"D:\path\to\world.mp4"},
)
```

I am not sure how the RequestController works in detail, but as you see, we add `notify.` in front of the subject, before we send it. Can you try doing that as well, as in:

```C#
RequestController.Send(new Dictionary<string, object>
{ 
    { "subject","notify.start_plugin" },
    { "name", "File_Source" },
    { "args", new Dictionary<string, object>
        {
            {"source_path:", @"D:\Work\my-double-checked-correct-path\log\log_20200212-1612\gaze\000\world.mp4"}
        }
    }
});
```

**Comment by dalind** [comment]
Thanks @pfaion .

They python script works for me.

In Unity/C#, unfortunately, it does not. The RequestController already appends "notify" to the _subject_ (more specifically, Request.cs / SendRequestMessage). My guess is that the args do not get serialized properly. I can check this later today.

If I cannot get this to work, I will call the Python script from Unity as last resort. But I don't think there is an inherent reason why it should not work.

**Comment by pfaion** [comment]
@fx-lange Any ideas why the notification via `RequestController.Send()` wouldn't work?

**Comment by papr** [comment]
@dalind Please try to escape the `\` characters.
```cs
{"source_path:", @"D:\\Work\\my-double-checked-correct-path\\log\\log_20200212-1612\\gaze\\000\\world.mp4"}
```

**Comment by papr** [comment]
@pfaion Maybe there should be a more explicit error message if the source path does not exist.

**Comment by pfaion** [comment]
@papr the `@` in the C# code already escapes the `\`

**Comment by papr** [comment]
@pfaion Ah did not know that.

@dalind You could use the [notification monitor script](/pupil-labs/hmd-eyes/blob/master/python_reference_client/notification_monitor.py) to check if your notification arrives as expected and compare it to the notification sent by @pfaion's example.

**Comment by papr** [comment]
```cs
string string1 = "This is a string created by assignment.";
Console.WriteLine(string1);
string string2a = "The path is C:\\PublicDocuments\\Report1.doc";
Console.WriteLine(string2a);
string string2b = @"The path is C:\PublicDocuments\Report1.doc";
Console.WriteLine(string2b);
// The example displays the following output:
//       This is a string created by assignment.
//       The path is C:\PublicDocuments\Report1.doc
//       The path is C:\PublicDocuments\Report1.doc  
```
@pfaion @dalind I still think that missing escaping is the issue. If you look at the example from the docs that @pfaion linked, cited above, the output does not contain the escape character anymore. This means that the path will be written without the escape character to the notification causing the interpretation in Capture to fail. The Python script actually sends a string with explicitly escaped `\\`.

**Comment by dalind** [comment]
One of those days where you doubt your life choices....

Here is the working command:

```
RequestController.Send(new Dictionary<string, object>
{
    { "subject","start_plugin" },
    { "name", "File_Source" },
    { "args", new Dictionary<string, object>
    {
        {"source_path", @"C:\Users\dalind\recordings\log\log_20200212-1543\gaze\000\world.mp4"}
    }}
})
```

It produces the following command in the notification_monitor:
`('notify.file_source.video_finished', {'subject': 'file_source.video_finished', 'source_path': 'C:\\Users\\dalind\\recordings\\log\\log_20200212-1543\\gaze\\000\\world.mp4', 'topic': 'notify.file_source.video_finished'})`

This is similar to the Python script. 

But why didn't it work before, you might wonder?

If you go back to the earlier post, you might notice the following line:
`{"source_path:", @"D:\..."}`
Notice the colon behind source_path? You don't need it, because that's just how the args list is built.


So, single escaping via @ or \\ (but not both) works fine. RequestController already appends _notify_, and the serialization works fine as well. 

**Thanks a ton @papr @pfaion !**

**Comment by pfaion** [comment]
Great to hear! Amazing that all of us did not notice the `:`, I was also triple-checking for any errors 😄

**Comment by dalind** [comment]
So, I can now replay videos for all 3 cameras (world, eye0, eye1). The issue that arises now concerns sync: although I start the videos sequentially with a delay of roughly 2 frames (10-15ms), the videos seem to have a delay of 0.5 - 1 seconds. 

I copied the eye0.mp4 and the timestamps and lookup as eye2, and played the 2 videos (one per eye). Even then, the videos are not (even close) synced.

Is there any command to start all videos simultaneously. Parallelizing the start does not work because of the ZMQ send-receive pattern (each send must have a receive afterwards).

Any suggestions would be great.

Thanks a lot!

**Comment by papr** [comment]
Please be aware that running file sources in Capture is a developer feature and only a workaround for your situation. In any case, you will have to consider the timestamp information of the data that is sent to Unity from Pupil Capture.

Pupil Capture does not synchronize the world and eye processes when running in real time either. Instead, the world process buffers pupil data, matches pupil data pairs based on their timestamp and maps these pairs to gaze data.

Revisiting your goal
> I want to record data in VR for multiple users and store all interactions, incl. gaze. After the experiment, I would like to replay what users did, and where they looked at. This will allow me to extract gaze data from multiple angles, and possibly for multiple cameras. In our context, we want to use it to test a ML model, and extract a data set.

I think you would save yourself a lot of trouble if you would not use the File Source in Pupil Capture workaround.

Instead, I would recommend reading the recorded gaze positions directly from the Pupil Capture recording files. This allows you to access the data instantly instead of waiting for Capture to replay everything. You would still need to correlate the recorded data (gaze + user view) by time but it would be much more efficient since you have not to account for any network/processing delays.

Specifically, you would read the data from the `gaze.pldata` files. See our developer documentation for its structure: https://docs.pupil-labs.com/developer/core/recording-format/#pldata-files

You should be able to reuse most of the msgpack-parsing code already available in hmd-eyes as these files contain the very same msgpack data that is sent to Unity via the network.

Please reopen a new issue if you should have any trouble with the suggested approach.

I will close this issue since the question regarding starting the File Source remotely has been solved.
