### ISSUE TITLE
HMD_Calibration(_3D) does not drop low-confidence samples

### ISSUE THREAD

**Issue by cboulay** [pupil-labs/hmd-eyes#89]
I was recently revisiting how the data from an experiment in Unity are calibrated so I can do calibration offline (adding more samples from periods with known good data), and I think that the gaze data are not being filtered.

Both [`HMD_Calibration`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/hmd_calibration.py#L120-L122) and [`HMD_Calibration_3D`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/hmd_calibration.py#L226) call [`get_data_for_calibration_hmd`](https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/calibration_routines/data_processing.py#L240). Unlike `get_data_for_calibration`, which has as its first step `_filter_pupil_list_by_confidence`, no filtering happens in `get_data_for_calibration_hmd`.

I thought that maybe confidence-based filtering might happen in Unity instead (maybe it once did?), but I couldn't find it.

Is this intentional?
Am I missing something?

**Comment by fx-lange** [comment]
Hi @cboulay - thanks for pointing this out. In Unity/hmd-eyes confidence based filtering only happens when receiving gaze data not during the calibration. We will look into it.

**Comment by papr** [comment]
This has been fixed in https://github.com/pupil-labs/pupil/pull/1867 Implementation: https://github.com/pupil-labs/pupil/blob/e6a8856d19175c7c5ff553edc942b5cbfde3a0ef/pupil_src/shared_modules/gaze_mapping/gazer_3d/gazer_hmd.py#L136-L138
