### ISSUE TITLE
How to make Gaze Visualizer invisible for the HMD-user?

### ISSUE THREAD

**Issue by bastianilso** [pupil-labs/hmd-eyes#90]
Hi pupil labs,

I was working on integration of Gaze Tracker prefab from hmd-eyes v1.1 which work very well. But I'm having difficulty keeping the gaze tracking visible only to people outside VR.

Do you have any examples/demos of how to do that?

**Comment by fx-lange** [comment]
Hi @bastianilso, sorry for the delay.

One option would be to deactivate the Gaze Visualizer in Unity and screencast to Pupil Capture https://github.com/pupil-labs/hmd-eyes/blob/master/docs/Developer.md#screencast. This would also allow to record at the same time. Be aware that this approach is quite heavy on the CPU and might be overkill for your usecase. 

Instead you could setup an additional camera (similar to the screencast setup) and only render the marker inside the extra camera but not in the VR camera. This can be done by assigning a layer to the marker and exclude this layer from the VR cam.

Hope this helps (if still relevant).
