### ISSUE TITLE
Live recording

### ISSUE THREAD

**Issue by LinusZeuwts** [pupil-labs/hmd-eyes#91]
We have a pupil labs vr/ar eye tracker installed on a HTC Vive. When an application is running with eye movement recording, would it be possible to save a video with the gaze cursor overlayed on what the participant saw in the application?

**Comment by fx-lange** [comment]
Hi @LinusZeuwts - yes that's possible. It requires Pupil Capture (instead of pupil service) and the Screencast component in hmd-eyes https://github.com/pupil-labs/hmd-eyes/blob/master/docs/Developer.md#screencast
